sudo: required

language: python
python: '2.7'

matrix:
  fast_finish: true
  include:
    - distribution: centos
      version: 7
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
      env: ANSIBLE_CENTOS=1
    - distribution: ubuntu
      version: 14.04
      init: /sbin/init
      run_opts: ""
      env: ANSIBLE_UBUNTU=1
    - env: DOCKER=1

install: true

services:
  - docker

script:
  - if [ -n "ANSIBLE_CENTOS" ]; then ./travis_testing/ansible.sh ; fi;
  - if [ -n "ANSIBLE_UBUNTU" ]; then ./travis_testing/ansible.sh ; fi;
  - if [ -n "DOCKER" ]; then ./travis_testing/docker.sh ; fi;

notifications:
  slack:
    rooms:
      secure: nPY+SvgkOrpvU76i55bDtXPbclq7WzY2DCwOCbYNzpMMTNnlqV9uhwUc31gHdl+xO8aXf52JwuOqTZnJTi9PGuomp7qf4N4z/dz3tKdjj3ppgeDx8hcmAikiM/qoOUadA9zNvP+wHfJSK7l6LnbAZgdOAXZb77Fk5rIuRr695vg=
    on_success: always
    on_failure: always
    on_start: always

after_success:
  - pip install coveralls; coveralls
