version: '2'

services:
  kafka_monitor:
    image: istresearch/scrapy-cluster:kafka-monitor
    build:
      context: .
      dockerfile: docker/kafka-monitor/Dockerfile
    depends_on:
      - kafka
      - redis
  redis_monitor:
    image: istresearch/scrapy-cluster:redis-monitor
    build:
      context: .
      dockerfile: docker/redis-monitor/Dockerfile
    depends_on:
      - kafka
      - redis
      - zookeeper
  crawler:
    image: istresearch/scrapy-cluster:crawler
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    depends_on:
      - kafka
      - redis
      - zookeeper
  redis:
    image: redis
    ports:
      - "6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
