version: '2'

services:
  kafka-monitor:
    image: istresearch/scrapy-cluster:kafka-monitor
    container_name: sc_kafka_monitor_1
    build:
      context: .
      dockerfile: docker/kafka-monitor/Dockerfile
    depends_on:
      - kafka
      - redis
  # redis-monitor:
  #   image: istresearch/scrapy-cluster:redis-monitor
  #   container_name: sc_redis_monitor_1
  #   build:
  #     context: .
  #     dockerfile: docker/redis-monitor/Dockerfile
  #   depends_on:
  #     - kafka
  #     - redis
  # crawler:
  #   image: istresearch/scrapy-cluster:crawler
  #   container_name: sc_crawler_1
  #   build:
  #     context: .
  #     dockerfile: docker/crawler/Dockerfile
  #   depends_on:
  #     - kafka
  #     - redis
  redis:
    container_name: sc_redis_1
    image: redis
    ports:
      - "6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: sc_zookeeper_1
    ports:
      - "2181:2181"
  kafka:
    container_name: sc_kafka_1
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
